spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: "crediya"

# External Services Configuration
external:
  services:
    auth:
      base-url: ${AUTH_SERVICE_BASE_URL:http://localhost:8090}
