spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:dev}"
  application:
    name: "crediya"
external:
  services:
    auth:
      base-url: "${AUTH_SERVICE_BASE_URL:http://localhost:8090}"
adapter:
  sqs:
    region: "us-east-2"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/013517326986/crediya-loan-decisions"
    endpoint: "" # Empty for real AWS, only needed for localstack
